package VS2;


/**
* VS2/array_of_MessageDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Monday, March 27, 2017 11:08:53 AM CEST
*/

public final class array_of_MessageDataHolder implements org.omg.CORBA.portable.Streamable
{
  public VS2.MessageData value[] = null;

  public array_of_MessageDataHolder ()
  {
  }

  public array_of_MessageDataHolder (VS2.MessageData[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = VS2.array_of_MessageDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    VS2.array_of_MessageDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return VS2.array_of_MessageDataHelper.type ();
  }

}
