package VS2;


/**
* VS2/array_of_StringHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Saturday, March 25, 2017 2:41:42 PM CET
*/


//Definition string[], da IDL nicht kennt
public final class array_of_StringHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public array_of_StringHolder ()
  {
  }

  public array_of_StringHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = VS2.array_of_StringHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    VS2.array_of_StringHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return VS2.array_of_StringHelper.type ();
  }

}
