package VS2;


/**
* VS2/LoginServerInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Monday, March 27, 2017 11:08:54 AM CEST
*/

abstract public class LoginServerInterfaceHelper
{
  private static String  _id = "IDL:VS2/LoginServerInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, VS2.LoginServerInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static VS2.LoginServerInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (VS2.LoginServerInterfaceHelper.id (), "LoginServerInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static VS2.LoginServerInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LoginServerInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, VS2.LoginServerInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static VS2.LoginServerInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof VS2.LoginServerInterface)
      return (VS2.LoginServerInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      VS2._LoginServerInterfaceStub stub = new VS2._LoginServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static VS2.LoginServerInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof VS2.LoginServerInterface)
      return (VS2.LoginServerInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      VS2._LoginServerInterfaceStub stub = new VS2._LoginServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
