package VS2;

/**
* VS2/LoginServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Saturday, March 25, 2017 2:41:42 PM CET
*/

public final class LoginServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public VS2.LoginServerInterface value = null;

  public LoginServerInterfaceHolder ()
  {
  }

  public LoginServerInterfaceHolder (VS2.LoginServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = VS2.LoginServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    VS2.LoginServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return VS2.LoginServerInterfaceHelper.type ();
  }

}
