package VS2;


/**
* VS2/LoginServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Monday, March 27, 2017 11:08:54 AM CEST
*/

public interface LoginServerInterface extends LoginServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LoginServerInterface
