package VS2;


/**
* VS2/MessageboardServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Saturday, March 25, 2017 2:41:42 PM CET
*/

public interface MessageboardServerInterface extends MessageboardServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MessageboardServerInterface
