package VS2;


/**
* VS2/UserData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Saturday, March 25, 2017 2:41:42 PM CET
*/

public final class UserData implements org.omg.CORBA.portable.IDLEntity
{
  public int userID = (int)0;
  public String userName = null;
  public String password = null;

  public UserData ()
  {
  } // ctor

  public UserData (int _userID, String _userName, String _password)
  {
    userID = _userID;
    userName = _userName;
    password = _password;
  } // ctor

} // class UserData
