/* soapStub.h
   Generated by gSOAP 2.8.44 for C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_NAMESPACE_OF_ns1	"http://webservice.tafelServer/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20844
# error "GSOAP VERSION 20844 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

class ns1__receiveMessage;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:137 */
class ns1__receiveMessageResponse;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:140 */
class ns1__deletePublicMessage;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:143 */
class ns1__deletePublicMessageResponse;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:146 */
class ns1__registerServer;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:149 */
class ns1__registerServerResponse;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:152 */
class ns1__modifyPublicMessage;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:155 */
class ns1__modifyPublicMessageResponse;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:158 */
class ns1__deleteMessageCorba;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:161 */
class ns1__deleteMessageCorbaResponse;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:164 */
class ns1__modifyMessageCorba;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:167 */
class ns1__modifyMessageCorbaResponse;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:170 */
class ns1__receiveMessageCorba;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:173 */
class ns1__receiveMessageCorbaResponse;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:176 */
struct __ns1__receiveMessage;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:725 */
struct __ns1__receiveMessageCorba;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:792 */
struct __ns1__deletePublicMessage;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:859 */
struct __ns1__deleteMessageCorba;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:926 */
struct __ns1__modifyPublicMessage;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:993 */
struct __ns1__modifyMessageCorba;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:1060 */
struct __ns1__registerServer;	/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:1127 */

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:137 */
#ifndef SOAP_TYPE_ns1__receiveMessage
#define SOAP_TYPE_ns1__receiveMessage (7)
/* complex XSD type 'ns1:receiveMessage': */
class SOAP_CMAC ns1__receiveMessage {
      public:
        /// Required element 'arg0' of XSD type 'xsd:int'
        int arg0;
        /// Required element 'arg1' of XSD type 'xsd:int'
        int arg1;
        /// Required element 'arg2' of XSD type 'xsd:int'
        int arg2;
        /// Optional element 'arg3' of XSD type 'xsd:string'
        char *arg3;
        /// Optional element 'arg4' of XSD type 'xsd:string'
        char *arg4;
        /// Required element 'arg5' of XSD type 'xsd:int'
        int arg5;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__receiveMessage
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__receiveMessage; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__receiveMessage, default initialized and not managed by a soap context
        virtual ns1__receiveMessage *soap_alloc(void) const { return SOAP_NEW(ns1__receiveMessage); }
      public:
        /// Constructor with initializations
        ns1__receiveMessage()
        {
          arg0 = (int)0;
          arg1 = (int)0;
          arg2 = (int)0;
          arg3 = (char *)0;
          arg4 = (char *)0;
          arg5 = (int)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__receiveMessage() { }
        /// Friend allocator used by soap_new_ns1__receiveMessage(struct soap*, int)
        friend SOAP_FMAC1 ns1__receiveMessage * SOAP_FMAC2 soap_instantiate_ns1__receiveMessage(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:140 */
#ifndef SOAP_TYPE_ns1__receiveMessageResponse
#define SOAP_TYPE_ns1__receiveMessageResponse (8)
/* complex XSD type 'ns1:receiveMessageResponse': */
class SOAP_CMAC ns1__receiveMessageResponse {
      public:
        /// Optional element 'return' of XSD type 'xsd:string'
        char *return_;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__receiveMessageResponse
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__receiveMessageResponse; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__receiveMessageResponse, default initialized and not managed by a soap context
        virtual ns1__receiveMessageResponse *soap_alloc(void) const { return SOAP_NEW(ns1__receiveMessageResponse); }
      public:
        /// Constructor with initializations
        ns1__receiveMessageResponse()
        {
          return_ = (char *)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__receiveMessageResponse() { }
        /// Friend allocator used by soap_new_ns1__receiveMessageResponse(struct soap*, int)
        friend SOAP_FMAC1 ns1__receiveMessageResponse * SOAP_FMAC2 soap_instantiate_ns1__receiveMessageResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:143 */
#ifndef SOAP_TYPE_ns1__deletePublicMessage
#define SOAP_TYPE_ns1__deletePublicMessage (9)
/* complex XSD type 'ns1:deletePublicMessage': */
class SOAP_CMAC ns1__deletePublicMessage {
      public:
        /// Required element 'arg0' of XSD type 'xsd:int'
        int arg0;
        /// Required element 'arg1' of XSD type 'xsd:int'
        int arg1;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__deletePublicMessage
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__deletePublicMessage; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__deletePublicMessage, default initialized and not managed by a soap context
        virtual ns1__deletePublicMessage *soap_alloc(void) const { return SOAP_NEW(ns1__deletePublicMessage); }
      public:
        /// Constructor with initializations
        ns1__deletePublicMessage()
        {
          arg0 = (int)0;
          arg1 = (int)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__deletePublicMessage() { }
        /// Friend allocator used by soap_new_ns1__deletePublicMessage(struct soap*, int)
        friend SOAP_FMAC1 ns1__deletePublicMessage * SOAP_FMAC2 soap_instantiate_ns1__deletePublicMessage(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:146 */
#ifndef SOAP_TYPE_ns1__deletePublicMessageResponse
#define SOAP_TYPE_ns1__deletePublicMessageResponse (10)
/* complex XSD type 'ns1:deletePublicMessageResponse': */
class SOAP_CMAC ns1__deletePublicMessageResponse {
      public:
        /// Optional element 'return' of XSD type 'xsd:string'
        char *return_;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__deletePublicMessageResponse
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__deletePublicMessageResponse; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__deletePublicMessageResponse, default initialized and not managed by a soap context
        virtual ns1__deletePublicMessageResponse *soap_alloc(void) const { return SOAP_NEW(ns1__deletePublicMessageResponse); }
      public:
        /// Constructor with initializations
        ns1__deletePublicMessageResponse()
        {
          return_ = (char *)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__deletePublicMessageResponse() { }
        /// Friend allocator used by soap_new_ns1__deletePublicMessageResponse(struct soap*, int)
        friend SOAP_FMAC1 ns1__deletePublicMessageResponse * SOAP_FMAC2 soap_instantiate_ns1__deletePublicMessageResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:149 */
#ifndef SOAP_TYPE_ns1__registerServer
#define SOAP_TYPE_ns1__registerServer (11)
/* complex XSD type 'ns1:registerServer': */
class SOAP_CMAC ns1__registerServer {
      public:
        /// Required element 'arg0' of XSD type 'xsd:int'
        int arg0;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__registerServer
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__registerServer; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__registerServer, default initialized and not managed by a soap context
        virtual ns1__registerServer *soap_alloc(void) const { return SOAP_NEW(ns1__registerServer); }
      public:
        /// Constructor with initializations
        ns1__registerServer()
        {
          arg0 = (int)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__registerServer() { }
        /// Friend allocator used by soap_new_ns1__registerServer(struct soap*, int)
        friend SOAP_FMAC1 ns1__registerServer * SOAP_FMAC2 soap_instantiate_ns1__registerServer(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:152 */
#ifndef SOAP_TYPE_ns1__registerServerResponse
#define SOAP_TYPE_ns1__registerServerResponse (12)
/* complex XSD type 'ns1:registerServerResponse': */
class SOAP_CMAC ns1__registerServerResponse {
      public:
        /// Optional element 'return' of XSD type 'xsd:string'
        char *return_;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__registerServerResponse
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__registerServerResponse; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__registerServerResponse, default initialized and not managed by a soap context
        virtual ns1__registerServerResponse *soap_alloc(void) const { return SOAP_NEW(ns1__registerServerResponse); }
      public:
        /// Constructor with initializations
        ns1__registerServerResponse()
        {
          return_ = (char *)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__registerServerResponse() { }
        /// Friend allocator used by soap_new_ns1__registerServerResponse(struct soap*, int)
        friend SOAP_FMAC1 ns1__registerServerResponse * SOAP_FMAC2 soap_instantiate_ns1__registerServerResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:155 */
#ifndef SOAP_TYPE_ns1__modifyPublicMessage
#define SOAP_TYPE_ns1__modifyPublicMessage (13)
/* complex XSD type 'ns1:modifyPublicMessage': */
class SOAP_CMAC ns1__modifyPublicMessage {
      public:
        /// Required element 'arg0' of XSD type 'xsd:int'
        int arg0;
        /// Optional element 'arg1' of XSD type 'xsd:string'
        char *arg1;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__modifyPublicMessage
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__modifyPublicMessage; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__modifyPublicMessage, default initialized and not managed by a soap context
        virtual ns1__modifyPublicMessage *soap_alloc(void) const { return SOAP_NEW(ns1__modifyPublicMessage); }
      public:
        /// Constructor with initializations
        ns1__modifyPublicMessage()
        {
          arg0 = (int)0;
          arg1 = (char *)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__modifyPublicMessage() { }
        /// Friend allocator used by soap_new_ns1__modifyPublicMessage(struct soap*, int)
        friend SOAP_FMAC1 ns1__modifyPublicMessage * SOAP_FMAC2 soap_instantiate_ns1__modifyPublicMessage(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:158 */
#ifndef SOAP_TYPE_ns1__modifyPublicMessageResponse
#define SOAP_TYPE_ns1__modifyPublicMessageResponse (14)
/* complex XSD type 'ns1:modifyPublicMessageResponse': */
class SOAP_CMAC ns1__modifyPublicMessageResponse {
      public:
        /// Optional element 'return' of XSD type 'xsd:string'
        char *return_;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__modifyPublicMessageResponse
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__modifyPublicMessageResponse; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__modifyPublicMessageResponse, default initialized and not managed by a soap context
        virtual ns1__modifyPublicMessageResponse *soap_alloc(void) const { return SOAP_NEW(ns1__modifyPublicMessageResponse); }
      public:
        /// Constructor with initializations
        ns1__modifyPublicMessageResponse()
        {
          return_ = (char *)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__modifyPublicMessageResponse() { }
        /// Friend allocator used by soap_new_ns1__modifyPublicMessageResponse(struct soap*, int)
        friend SOAP_FMAC1 ns1__modifyPublicMessageResponse * SOAP_FMAC2 soap_instantiate_ns1__modifyPublicMessageResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:161 */
#ifndef SOAP_TYPE_ns1__deleteMessageCorba
#define SOAP_TYPE_ns1__deleteMessageCorba (15)
/* complex XSD type 'ns1:deleteMessageCorba': */
class SOAP_CMAC ns1__deleteMessageCorba {
      public:
        /// Required element 'arg0' of XSD type 'xsd:int'
        int arg0;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__deleteMessageCorba
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__deleteMessageCorba; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__deleteMessageCorba, default initialized and not managed by a soap context
        virtual ns1__deleteMessageCorba *soap_alloc(void) const { return SOAP_NEW(ns1__deleteMessageCorba); }
      public:
        /// Constructor with initializations
        ns1__deleteMessageCorba()
        {
          arg0 = (int)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__deleteMessageCorba() { }
        /// Friend allocator used by soap_new_ns1__deleteMessageCorba(struct soap*, int)
        friend SOAP_FMAC1 ns1__deleteMessageCorba * SOAP_FMAC2 soap_instantiate_ns1__deleteMessageCorba(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:164 */
#ifndef SOAP_TYPE_ns1__deleteMessageCorbaResponse
#define SOAP_TYPE_ns1__deleteMessageCorbaResponse (16)
/* complex XSD type 'ns1:deleteMessageCorbaResponse': */
class SOAP_CMAC ns1__deleteMessageCorbaResponse {
      public:
        /// Optional element 'return' of XSD type 'xsd:string'
        char *return_;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__deleteMessageCorbaResponse
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__deleteMessageCorbaResponse; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__deleteMessageCorbaResponse, default initialized and not managed by a soap context
        virtual ns1__deleteMessageCorbaResponse *soap_alloc(void) const { return SOAP_NEW(ns1__deleteMessageCorbaResponse); }
      public:
        /// Constructor with initializations
        ns1__deleteMessageCorbaResponse()
        {
          return_ = (char *)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__deleteMessageCorbaResponse() { }
        /// Friend allocator used by soap_new_ns1__deleteMessageCorbaResponse(struct soap*, int)
        friend SOAP_FMAC1 ns1__deleteMessageCorbaResponse * SOAP_FMAC2 soap_instantiate_ns1__deleteMessageCorbaResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:167 */
#ifndef SOAP_TYPE_ns1__modifyMessageCorba
#define SOAP_TYPE_ns1__modifyMessageCorba (17)
/* complex XSD type 'ns1:modifyMessageCorba': */
class SOAP_CMAC ns1__modifyMessageCorba {
      public:
        /// Required element 'arg0' of XSD type 'xsd:int'
        int arg0;
        /// Optional element 'arg1' of XSD type 'xsd:string'
        char *arg1;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__modifyMessageCorba
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__modifyMessageCorba; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__modifyMessageCorba, default initialized and not managed by a soap context
        virtual ns1__modifyMessageCorba *soap_alloc(void) const { return SOAP_NEW(ns1__modifyMessageCorba); }
      public:
        /// Constructor with initializations
        ns1__modifyMessageCorba()
        {
          arg0 = (int)0;
          arg1 = (char *)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__modifyMessageCorba() { }
        /// Friend allocator used by soap_new_ns1__modifyMessageCorba(struct soap*, int)
        friend SOAP_FMAC1 ns1__modifyMessageCorba * SOAP_FMAC2 soap_instantiate_ns1__modifyMessageCorba(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:170 */
#ifndef SOAP_TYPE_ns1__modifyMessageCorbaResponse
#define SOAP_TYPE_ns1__modifyMessageCorbaResponse (18)
/* complex XSD type 'ns1:modifyMessageCorbaResponse': */
class SOAP_CMAC ns1__modifyMessageCorbaResponse {
      public:
        /// Optional element 'return' of XSD type 'xsd:string'
        char *return_;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__modifyMessageCorbaResponse
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__modifyMessageCorbaResponse; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__modifyMessageCorbaResponse, default initialized and not managed by a soap context
        virtual ns1__modifyMessageCorbaResponse *soap_alloc(void) const { return SOAP_NEW(ns1__modifyMessageCorbaResponse); }
      public:
        /// Constructor with initializations
        ns1__modifyMessageCorbaResponse()
        {
          return_ = (char *)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__modifyMessageCorbaResponse() { }
        /// Friend allocator used by soap_new_ns1__modifyMessageCorbaResponse(struct soap*, int)
        friend SOAP_FMAC1 ns1__modifyMessageCorbaResponse * SOAP_FMAC2 soap_instantiate_ns1__modifyMessageCorbaResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:173 */
#ifndef SOAP_TYPE_ns1__receiveMessageCorba
#define SOAP_TYPE_ns1__receiveMessageCorba (19)
/* complex XSD type 'ns1:receiveMessageCorba': */
class SOAP_CMAC ns1__receiveMessageCorba {
      public:
        /// Required element 'arg0' of XSD type 'xsd:int'
        int arg0;
        /// Required element 'arg1' of XSD type 'xsd:int'
        int arg1;
        /// Required element 'arg2' of XSD type 'xsd:int'
        int arg2;
        /// Optional element 'arg3' of XSD type 'xsd:string'
        char *arg3;
        /// Optional element 'arg4' of XSD type 'xsd:string'
        char *arg4;
        /// Required element 'arg5' of XSD type 'xsd:boolean'
        bool arg5;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__receiveMessageCorba
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__receiveMessageCorba; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__receiveMessageCorba, default initialized and not managed by a soap context
        virtual ns1__receiveMessageCorba *soap_alloc(void) const { return SOAP_NEW(ns1__receiveMessageCorba); }
      public:
        /// Constructor with initializations
        ns1__receiveMessageCorba()
        {
          arg0 = (int)0;
          arg1 = (int)0;
          arg2 = (int)0;
          arg3 = (char *)0;
          arg4 = (char *)0;
          arg5 = (bool)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__receiveMessageCorba() { }
        /// Friend allocator used by soap_new_ns1__receiveMessageCorba(struct soap*, int)
        friend SOAP_FMAC1 ns1__receiveMessageCorba * SOAP_FMAC2 soap_instantiate_ns1__receiveMessageCorba(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:176 */
#ifndef SOAP_TYPE_ns1__receiveMessageCorbaResponse
#define SOAP_TYPE_ns1__receiveMessageCorbaResponse (20)
/* complex XSD type 'ns1:receiveMessageCorbaResponse': */
class SOAP_CMAC ns1__receiveMessageCorbaResponse {
      public:
        /// Optional element 'return' of XSD type 'xsd:string'
        char *return_;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns1__receiveMessageCorbaResponse
        virtual int soap_type(void) const { return SOAP_TYPE_ns1__receiveMessageCorbaResponse; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns1__receiveMessageCorbaResponse, default initialized and not managed by a soap context
        virtual ns1__receiveMessageCorbaResponse *soap_alloc(void) const { return SOAP_NEW(ns1__receiveMessageCorbaResponse); }
      public:
        /// Constructor with initializations
        ns1__receiveMessageCorbaResponse()
        {
          return_ = (char *)0;
          soap = (struct soap *)0;
        }
        virtual ~ns1__receiveMessageCorbaResponse() { }
        /// Friend allocator used by soap_new_ns1__receiveMessageCorbaResponse(struct soap*, int)
        friend SOAP_FMAC1 ns1__receiveMessageCorbaResponse * SOAP_FMAC2 soap_instantiate_ns1__receiveMessageCorbaResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:725 */
#ifndef SOAP_TYPE___ns1__receiveMessage
#define SOAP_TYPE___ns1__receiveMessage (26)
/* Wrapper: */
struct SOAP_CMAC __ns1__receiveMessage {
      public:
        /** Optional element 'ns1:receiveMessage' of XSD type 'ns1:receiveMessage' */
        ns1__receiveMessage *ns1__receiveMessage_;
      public:
        /** Return unique type id SOAP_TYPE___ns1__receiveMessage */
        int soap_type() const { return SOAP_TYPE___ns1__receiveMessage; }
        /** Constructor with member initializations */
        __ns1__receiveMessage()
        {
          ns1__receiveMessage_ = (ns1__receiveMessage *)0;
        }
        /** Friend allocator used by soap_new___ns1__receiveMessage(struct soap*, int) */
        friend SOAP_FMAC1 __ns1__receiveMessage * SOAP_FMAC2 soap_instantiate___ns1__receiveMessage(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:792 */
#ifndef SOAP_TYPE___ns1__receiveMessageCorba
#define SOAP_TYPE___ns1__receiveMessageCorba (30)
/* Wrapper: */
struct SOAP_CMAC __ns1__receiveMessageCorba {
      public:
        /** Optional element 'ns1:receiveMessageCorba' of XSD type 'ns1:receiveMessageCorba' */
        ns1__receiveMessageCorba *ns1__receiveMessageCorba_;
      public:
        /** Return unique type id SOAP_TYPE___ns1__receiveMessageCorba */
        int soap_type() const { return SOAP_TYPE___ns1__receiveMessageCorba; }
        /** Constructor with member initializations */
        __ns1__receiveMessageCorba()
        {
          ns1__receiveMessageCorba_ = (ns1__receiveMessageCorba *)0;
        }
        /** Friend allocator used by soap_new___ns1__receiveMessageCorba(struct soap*, int) */
        friend SOAP_FMAC1 __ns1__receiveMessageCorba * SOAP_FMAC2 soap_instantiate___ns1__receiveMessageCorba(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:859 */
#ifndef SOAP_TYPE___ns1__deletePublicMessage
#define SOAP_TYPE___ns1__deletePublicMessage (34)
/* Wrapper: */
struct SOAP_CMAC __ns1__deletePublicMessage {
      public:
        /** Optional element 'ns1:deletePublicMessage' of XSD type 'ns1:deletePublicMessage' */
        ns1__deletePublicMessage *ns1__deletePublicMessage_;
      public:
        /** Return unique type id SOAP_TYPE___ns1__deletePublicMessage */
        int soap_type() const { return SOAP_TYPE___ns1__deletePublicMessage; }
        /** Constructor with member initializations */
        __ns1__deletePublicMessage()
        {
          ns1__deletePublicMessage_ = (ns1__deletePublicMessage *)0;
        }
        /** Friend allocator used by soap_new___ns1__deletePublicMessage(struct soap*, int) */
        friend SOAP_FMAC1 __ns1__deletePublicMessage * SOAP_FMAC2 soap_instantiate___ns1__deletePublicMessage(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:926 */
#ifndef SOAP_TYPE___ns1__deleteMessageCorba
#define SOAP_TYPE___ns1__deleteMessageCorba (38)
/* Wrapper: */
struct SOAP_CMAC __ns1__deleteMessageCorba {
      public:
        /** Optional element 'ns1:deleteMessageCorba' of XSD type 'ns1:deleteMessageCorba' */
        ns1__deleteMessageCorba *ns1__deleteMessageCorba_;
      public:
        /** Return unique type id SOAP_TYPE___ns1__deleteMessageCorba */
        int soap_type() const { return SOAP_TYPE___ns1__deleteMessageCorba; }
        /** Constructor with member initializations */
        __ns1__deleteMessageCorba()
        {
          ns1__deleteMessageCorba_ = (ns1__deleteMessageCorba *)0;
        }
        /** Friend allocator used by soap_new___ns1__deleteMessageCorba(struct soap*, int) */
        friend SOAP_FMAC1 __ns1__deleteMessageCorba * SOAP_FMAC2 soap_instantiate___ns1__deleteMessageCorba(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:993 */
#ifndef SOAP_TYPE___ns1__modifyPublicMessage
#define SOAP_TYPE___ns1__modifyPublicMessage (42)
/* Wrapper: */
struct SOAP_CMAC __ns1__modifyPublicMessage {
      public:
        /** Optional element 'ns1:modifyPublicMessage' of XSD type 'ns1:modifyPublicMessage' */
        ns1__modifyPublicMessage *ns1__modifyPublicMessage_;
      public:
        /** Return unique type id SOAP_TYPE___ns1__modifyPublicMessage */
        int soap_type() const { return SOAP_TYPE___ns1__modifyPublicMessage; }
        /** Constructor with member initializations */
        __ns1__modifyPublicMessage()
        {
          ns1__modifyPublicMessage_ = (ns1__modifyPublicMessage *)0;
        }
        /** Friend allocator used by soap_new___ns1__modifyPublicMessage(struct soap*, int) */
        friend SOAP_FMAC1 __ns1__modifyPublicMessage * SOAP_FMAC2 soap_instantiate___ns1__modifyPublicMessage(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:1060 */
#ifndef SOAP_TYPE___ns1__modifyMessageCorba
#define SOAP_TYPE___ns1__modifyMessageCorba (46)
/* Wrapper: */
struct SOAP_CMAC __ns1__modifyMessageCorba {
      public:
        /** Optional element 'ns1:modifyMessageCorba' of XSD type 'ns1:modifyMessageCorba' */
        ns1__modifyMessageCorba *ns1__modifyMessageCorba_;
      public:
        /** Return unique type id SOAP_TYPE___ns1__modifyMessageCorba */
        int soap_type() const { return SOAP_TYPE___ns1__modifyMessageCorba; }
        /** Constructor with member initializations */
        __ns1__modifyMessageCorba()
        {
          ns1__modifyMessageCorba_ = (ns1__modifyMessageCorba *)0;
        }
        /** Friend allocator used by soap_new___ns1__modifyMessageCorba(struct soap*, int) */
        friend SOAP_FMAC1 __ns1__modifyMessageCorba * SOAP_FMAC2 soap_instantiate___ns1__modifyMessageCorba(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:1127 */
#ifndef SOAP_TYPE___ns1__registerServer
#define SOAP_TYPE___ns1__registerServer (50)
/* Wrapper: */
struct SOAP_CMAC __ns1__registerServer {
      public:
        /** Optional element 'ns1:registerServer' of XSD type 'ns1:registerServer' */
        ns1__registerServer *ns1__registerServer_;
      public:
        /** Return unique type id SOAP_TYPE___ns1__registerServer */
        int soap_type() const { return SOAP_TYPE___ns1__registerServer; }
        /** Constructor with member initializations */
        __ns1__registerServer()
        {
          ns1__registerServer_ = (ns1__registerServer *)0;
        }
        /** Friend allocator used by soap_new___ns1__registerServer(struct soap*, int) */
        friend SOAP_FMAC1 __ns1__registerServer * SOAP_FMAC2 soap_instantiate___ns1__registerServer(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:1218 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (51)
/* SOAP_ENV__Header: */
struct SOAP_CMAC SOAP_ENV__Header {
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Header */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header()
        {
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Header(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:1218 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (52)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_CMAC SOAP_ENV__Code {
      public:
        /** Optional element 'SOAP-ENV:Value' of XSD type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Code */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Code; }
        /** Constructor with member initializations */
        SOAP_ENV__Code()
        {
          SOAP_ENV__Value = (char *)0;
          SOAP_ENV__Subcode = (struct SOAP_ENV__Code *)0;
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Code(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:1218 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (54)
/* SOAP_ENV__Detail: */
struct SOAP_CMAC SOAP_ENV__Detail {
      public:
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Detail */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail()
        {
          __any = (char *)0;
          __type = 0;
          fault = NULL;
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Detail(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:1218 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (57)
/* SOAP_ENV__Reason: */
struct SOAP_CMAC SOAP_ENV__Reason {
      public:
        /** Optional element 'SOAP-ENV:Text' of XSD type 'xsd:string' */
        char *SOAP_ENV__Text;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Reason */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Reason; }
        /** Constructor with member initializations */
        SOAP_ENV__Reason()
        {
          SOAP_ENV__Text = (char *)0;
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Reason(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:1218 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (58)
/* SOAP_ENV__Fault: */
struct SOAP_CMAC SOAP_ENV__Fault {
      public:
        /** Optional element 'faultcode' of XSD type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XSD type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XSD type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XSD type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XSD type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XSD type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Fault */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Fault; }
        /** Constructor with member initializations */
        SOAP_ENV__Fault()
        {
          faultcode = (char *)0;
          faultstring = (char *)0;
          faultactor = (char *)0;
          detail = (struct SOAP_ENV__Detail *)0;
          SOAP_ENV__Code = (struct SOAP_ENV__Code *)0;
          SOAP_ENV__Reason = (struct SOAP_ENV__Reason *)0;
          SOAP_ENV__Node = (char *)0;
          SOAP_ENV__Role = (char *)0;
          SOAP_ENV__Detail = (struct SOAP_ENV__Detail *)0;
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Fault(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:119 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

/* C:\GIT\VS22\Client_C++\src\serverCom\serverCom.h:119 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* bool has binding name 'bool' for type 'xsd:boolean' */
#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (22)
#endif

/* ns1__receiveMessageCorbaResponse has binding name 'ns1__receiveMessageCorbaResponse' for type 'ns1:receiveMessageCorbaResponse' */
#ifndef SOAP_TYPE_ns1__receiveMessageCorbaResponse
#define SOAP_TYPE_ns1__receiveMessageCorbaResponse (20)
#endif

/* ns1__receiveMessageCorba has binding name 'ns1__receiveMessageCorba' for type 'ns1:receiveMessageCorba' */
#ifndef SOAP_TYPE_ns1__receiveMessageCorba
#define SOAP_TYPE_ns1__receiveMessageCorba (19)
#endif

/* ns1__modifyMessageCorbaResponse has binding name 'ns1__modifyMessageCorbaResponse' for type 'ns1:modifyMessageCorbaResponse' */
#ifndef SOAP_TYPE_ns1__modifyMessageCorbaResponse
#define SOAP_TYPE_ns1__modifyMessageCorbaResponse (18)
#endif

/* ns1__modifyMessageCorba has binding name 'ns1__modifyMessageCorba' for type 'ns1:modifyMessageCorba' */
#ifndef SOAP_TYPE_ns1__modifyMessageCorba
#define SOAP_TYPE_ns1__modifyMessageCorba (17)
#endif

/* ns1__deleteMessageCorbaResponse has binding name 'ns1__deleteMessageCorbaResponse' for type 'ns1:deleteMessageCorbaResponse' */
#ifndef SOAP_TYPE_ns1__deleteMessageCorbaResponse
#define SOAP_TYPE_ns1__deleteMessageCorbaResponse (16)
#endif

/* ns1__deleteMessageCorba has binding name 'ns1__deleteMessageCorba' for type 'ns1:deleteMessageCorba' */
#ifndef SOAP_TYPE_ns1__deleteMessageCorba
#define SOAP_TYPE_ns1__deleteMessageCorba (15)
#endif

/* ns1__modifyPublicMessageResponse has binding name 'ns1__modifyPublicMessageResponse' for type 'ns1:modifyPublicMessageResponse' */
#ifndef SOAP_TYPE_ns1__modifyPublicMessageResponse
#define SOAP_TYPE_ns1__modifyPublicMessageResponse (14)
#endif

/* ns1__modifyPublicMessage has binding name 'ns1__modifyPublicMessage' for type 'ns1:modifyPublicMessage' */
#ifndef SOAP_TYPE_ns1__modifyPublicMessage
#define SOAP_TYPE_ns1__modifyPublicMessage (13)
#endif

/* ns1__registerServerResponse has binding name 'ns1__registerServerResponse' for type 'ns1:registerServerResponse' */
#ifndef SOAP_TYPE_ns1__registerServerResponse
#define SOAP_TYPE_ns1__registerServerResponse (12)
#endif

/* ns1__registerServer has binding name 'ns1__registerServer' for type 'ns1:registerServer' */
#ifndef SOAP_TYPE_ns1__registerServer
#define SOAP_TYPE_ns1__registerServer (11)
#endif

/* ns1__deletePublicMessageResponse has binding name 'ns1__deletePublicMessageResponse' for type 'ns1:deletePublicMessageResponse' */
#ifndef SOAP_TYPE_ns1__deletePublicMessageResponse
#define SOAP_TYPE_ns1__deletePublicMessageResponse (10)
#endif

/* ns1__deletePublicMessage has binding name 'ns1__deletePublicMessage' for type 'ns1:deletePublicMessage' */
#ifndef SOAP_TYPE_ns1__deletePublicMessage
#define SOAP_TYPE_ns1__deletePublicMessage (9)
#endif

/* ns1__receiveMessageResponse has binding name 'ns1__receiveMessageResponse' for type 'ns1:receiveMessageResponse' */
#ifndef SOAP_TYPE_ns1__receiveMessageResponse
#define SOAP_TYPE_ns1__receiveMessageResponse (8)
#endif

/* ns1__receiveMessage has binding name 'ns1__receiveMessage' for type 'ns1:receiveMessage' */
#ifndef SOAP_TYPE_ns1__receiveMessage
#define SOAP_TYPE_ns1__receiveMessage (7)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (58)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (57)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (54)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (52)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (51)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (60)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (59)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (53)
#endif

/* ns1__registerServer * has binding name 'PointerTons1__registerServer' for type 'ns1:registerServer' */
#ifndef SOAP_TYPE_PointerTons1__registerServer
#define SOAP_TYPE_PointerTons1__registerServer (47)
#endif

/* ns1__modifyMessageCorba * has binding name 'PointerTons1__modifyMessageCorba' for type 'ns1:modifyMessageCorba' */
#ifndef SOAP_TYPE_PointerTons1__modifyMessageCorba
#define SOAP_TYPE_PointerTons1__modifyMessageCorba (43)
#endif

/* ns1__modifyPublicMessage * has binding name 'PointerTons1__modifyPublicMessage' for type 'ns1:modifyPublicMessage' */
#ifndef SOAP_TYPE_PointerTons1__modifyPublicMessage
#define SOAP_TYPE_PointerTons1__modifyPublicMessage (39)
#endif

/* ns1__deleteMessageCorba * has binding name 'PointerTons1__deleteMessageCorba' for type 'ns1:deleteMessageCorba' */
#ifndef SOAP_TYPE_PointerTons1__deleteMessageCorba
#define SOAP_TYPE_PointerTons1__deleteMessageCorba (35)
#endif

/* ns1__deletePublicMessage * has binding name 'PointerTons1__deletePublicMessage' for type 'ns1:deletePublicMessage' */
#ifndef SOAP_TYPE_PointerTons1__deletePublicMessage
#define SOAP_TYPE_PointerTons1__deletePublicMessage (31)
#endif

/* ns1__receiveMessageCorba * has binding name 'PointerTons1__receiveMessageCorba' for type 'ns1:receiveMessageCorba' */
#ifndef SOAP_TYPE_PointerTons1__receiveMessageCorba
#define SOAP_TYPE_PointerTons1__receiveMessageCorba (27)
#endif

/* ns1__receiveMessage * has binding name 'PointerTons1__receiveMessage' for type 'ns1:receiveMessage' */
#ifndef SOAP_TYPE_PointerTons1__receiveMessage
#define SOAP_TYPE_PointerTons1__receiveMessage (23)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
