package corbaConnect;

/**
* VS2/LoginServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Monday, March 27, 2017 11:08:54 AM CEST
*/

public final class LoginServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public corbaConnect.LoginServerInterface value = null;

  public LoginServerInterfaceHolder ()
  {
  }

  public LoginServerInterfaceHolder (corbaConnect.LoginServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbaConnect.LoginServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbaConnect.LoginServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbaConnect.LoginServerInterfaceHelper.type ();
  }

}
