package corbaConnect;


/**
* VS2/LoginServerInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Sonntag, 26. März 2017 18:12 Uhr MESZ
*/

public abstract class LoginServerInterfacePOA extends org.omg.PortableServer.Servant
 implements corbaConnect.LoginServerInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("reg", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // VS2/LoginServerInterface/login
       {
         corbaConnect.UserData uData = corbaConnect.UserDataHelper.read (in);
         corbaConnect.LoginInformation $result = null;
         $result = this.login (uData);
         out = $rh.createReply();
         corbaConnect.LoginInformationHelper.write (out, $result);
         break;
       }

       case 1:  // VS2/LoginServerInterface/reg
       {
         corbaConnect.UserData uData = corbaConnect.UserDataHelper.read (in);
         String regData = in.read_string ();
         boolean $result = false;
         $result = this.reg (uData, regData);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:VS2/LoginServerInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public LoginServerInterface _this() 
  {
    return LoginServerInterfaceHelper.narrow(
    super._this_object());
  }

  public LoginServerInterface _this(org.omg.CORBA.ORB orb) 
  {
    return LoginServerInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class LoginServerInterfacePOA
