package corbaConnect;


/**
* VS2/MessageboardServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VS2.idl
* Monday, March 27, 2017 11:08:54 AM CEST
*/

public interface MessageboardServerInterfaceOperations 
{
  String getFatherName ();

  //MessageBoard hat fatherId-> abruf xml datei auf fathername
  String[] getChildNames ();
  corbaConnect.MessageData[] getMessages ();
  corbaConnect.MessageData setHighlightedMessage (String messageID);
  corbaConnect.MessageData getHighlightedMessage ();
  corbaConnect.MessageData getMessageWithId (String messageID);
  boolean setMessage (String message, String messageID, corbaConnect.UserData uData);
  boolean deleteMessage (String messageID, corbaConnect.UserData uData);
  boolean createNewMessage (String message, corbaConnect.UserData uData);
  corbaConnect.MessageData getNextMessage ();
  corbaConnect.MessageData getPreviousMessage ();
  corbaConnect.ConnectInformationData connectToFather (corbaConnect.UserData uData);

  //Liefert die Connectinformationen des Fathers
  corbaConnect.ConnectInformationData connectToChild (String childName);

  //********** zur Kommunikation zwischen Servern(Spezialfälle, daher notwendig) muss nicht in den Client rein ************************
  boolean publishOnChilds (String message, String messageID, corbaConnect.UserData uData, boolean schalter);

  //Die Nachricht auf allen Kindern veröffentlichen, extra Schalter um auf allen Kindes Kindern zu veröffentlichen?
  boolean publishOnFather (String message, String messageID, corbaConnect.UserData uData);

  //Nachricht auf Vater veröffentlichen
  boolean saveMessage (String message, String messageID, corbaConnect.UserData uData);

  //Wird beim ausführen von publishOnXXX aufgerufen
  void notifyFather (corbaConnect.UserData uData);

  //gebe dem Vater bescheid das du jetzt ein Kind von ihm bist
  void saveFatherInformation (int id, String name, corbaConnect.ConnectInformationData ciData, corbaConnect.UserData uData);
  void notifyChildren (corbaConnect.UserData uData);

  //gebe den Kindern bescheid das du jetzt der Vater bist
  void saveChildInformation (int id, String name, corbaConnect.ConnectInformationData ciData, corbaConnect.UserData uData);

  //Method Calls für SOAP-Server
  boolean createMessageSoap (String message, String messageID, int serverNr, corbaConnect.UserData uData);
  boolean modifyMessageSoap (String message, String messageID, int serverNr, corbaConnect.UserData uData);
  boolean deleteMessageSoap (String messageID, corbaConnect.UserData uData);
} // interface MessageboardServerInterfaceOperations
